name = "craz-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "3cf7dfb6565142a3b880566723de8435"

[env.production]
name = "craz-api"
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "your-production-kv-namespace-id" 